import { subjectPederationTypes, onlyPovTypes } from 'components/tourism/tourism-data/city-types';

export const MAP_POINT_MAP = {
	TOTAL: 'TOTAL',
	RUSSIA: 'RUSSIA',
	WORLD: 'WORLD',
	MOSCOW_ADM_ORKUG: 'MOSCOW_ADM_ORKUG',
	MOSCOW_TOWN: 'MOSCOW_TOWN',
	MOSCOW_DISTRICT: 'MOSCOW_DISTRICT',
	METRO_MOSCOW: 'METRO_MOSCOW',
	FEDERATION_SUBJECT: 'FEDERATION_SUBJECT',
	FEDERATION_REPUBLIC: 'FEDERATION_REPUBLIC',
	FEDERATION_KRAY: 'FEDERATION_KRAY',
	FEDERATION_OBLAST: 'FEDERATION_OBLAST',
	FEDERATION_MEGACITY: 'FEDERATION_MEGACITY',
	FEDERATION_AVTONOM: 'FEDERATION_AVTONOM',
	ONLY_POV: 'ONLY_POV',
	DEAD_TOWN: 'DEAD_TOWN',
	CASTLE: 'CASTLE',
	CANYON: 'CANYON',
	PARK: 'PARK',
	MONASTERY: 'MONASTERY',
	QUARRY: 'QUARRY',
	CITY: 'CITY',
	VILLAGE: 'VILLAGE',
	ZATO: 'ZATO',
} as const
export const typeFilters = {
	[MAP_POINT_MAP.MOSCOW_ADM_ORKUG]: ['административный округ Москвы', 'округ Москвы'],
	[MAP_POINT_MAP.MOSCOW_TOWN]: ['поселение Москвы'],
	[MAP_POINT_MAP.MOSCOW_DISTRICT]: ['район Москвы'],
	[MAP_POINT_MAP.METRO_MOSCOW]: ['метро Москвы'],
	[MAP_POINT_MAP.FEDERATION_SUBJECT]: subjectPederationTypes,
	[MAP_POINT_MAP.FEDERATION_REPUBLIC]: ['республика'],
	[MAP_POINT_MAP.FEDERATION_KRAY]: ['край'],
	[MAP_POINT_MAP.FEDERATION_OBLAST]: ['область'],
	[MAP_POINT_MAP.FEDERATION_MEGACITY]: ['город федерального значения'],
	[MAP_POINT_MAP.FEDERATION_AVTONOM]: ['автономный область', 'автономный округ'],
	[MAP_POINT_MAP.ONLY_POV]: onlyPovTypes,
	[MAP_POINT_MAP.DEAD_TOWN]: ['вымерший город'],
	[MAP_POINT_MAP.CASTLE]: ['крепость'],
	[MAP_POINT_MAP.CANYON]: ['каньон'],
	[MAP_POINT_MAP.PARK]: ['парк'],
	[MAP_POINT_MAP.MONASTERY]: ['монастырь'],
	[MAP_POINT_MAP.QUARRY]: ['каменоломни'],
	[MAP_POINT_MAP.CITY]: ['город'],
	[MAP_POINT_MAP.VILLAGE]: ['деревня'],
	[MAP_POINT_MAP.ZATO]: ['ЗАТО'],
} as const
